import dayjs from "dayjs";
import { getCompletedDaysLate } from "./dateUtils";

/**
 * Calcule le Score de Productivité (0–100) pour une période donnée.
 * Algorithme pondéré : tâches 50% + habitudes 30% + pomodoro 10% + streak 10%
 */
export function calculateProductivityScore({
  tasksTotal = 0,
  tasksDone = 0,
  habitsTotal = 0,
  habitsDone = 0,
  pomodoroSessions = 0,
  currentStreak = 0,
}) {
  const taskRate = tasksTotal > 0 ? (tasksDone / tasksTotal) * 100 : 0;
  const habitRate = habitsTotal > 0 ? (habitsDone / habitsTotal) * 100 : 0;
  // Pomodoro: 4 sessions = 100%, capped
  const pomodoroRate = Math.min((pomodoroSessions / 4) * 100, 100);
  // Streak bonus: jusqu'à 10 pts pour streak ≥ 7 jours
  const streakBonus = Math.min((currentStreak / 7) * 10, 10);

  const score =
    taskRate * 0.5 + habitRate * 0.3 + pomodoroRate * 0.1 + streakBonus;

  return Math.round(Math.min(score, 100));
}

/**
 * Catégorise le score en niveau avec label et couleur
 */
export function getScoreLevel(score) {
  if (score >= 90)
    return { label: "Exceptionnel 🏆", color: "#F59E0B", emoji: "🏆" };
  if (score >= 75)
    return { label: "Excellent 🔥", color: "#10B981", emoji: "🔥" };
  if (score >= 60)
    return { label: "Bon travail 😊", color: "#06B6D4", emoji: "😊" };
  if (score >= 40)
    return { label: "En progrès 💪", color: "#7C3AED", emoji: "💪" };
  if (score >= 20)
    return { label: "Difficile 😓", color: "#F59E0B", emoji: "😓" };
  return { label: "Journée dure 😞", color: "#EF4444", emoji: "😞" };
}

/**
 * Génère un rapport quotidien à partir des données en temps réel.
 * Ce rapport est sauvegardé dans Firestore si absent.
 */
export function generateDailyReport({
  tasks,
  habits,
  pomodoroData,
  currentStreak,
  dateStr,
}) {
  const today = dateStr || dayjs().format("YYYY-MM-DD");

  // Tâches du jour (date = aujourd'hui, ou terminées aujourd'hui)
  const todayCompleted = tasks.filter(
    (t) =>
      t.done &&
      t.completedAt &&
      dayjs(t.completedAt).format("YYYY-MM-DD") === today,
  );
  const todayTasks = tasks.filter((t) => t.date === today);
  const todayDone = todayTasks.filter((t) => t.done).length;
  const todayLate = todayCompleted.filter(
    (t) => getCompletedDaysLate(t) > 0,
  ).length;

  // Habitudes du jour
  const habitsTotal = habits.length;
  const habitsDone = habits.filter((h) =>
    (h.completedDates || []).includes(today),
  ).length;

  // Score
  const score = calculateProductivityScore({
    tasksTotal: todayTasks.length,
    tasksDone: todayDone,
    habitsTotal,
    habitsDone,
    pomodoroSessions: pomodoroData?.sessions || 0,
    currentStreak,
  });

  return {
    type: "daily",
    periodStart: today,
    periodEnd: today,
    tasksTotal: todayTasks.length,
    tasksDone: todayDone,
    tasksLate: todayLate,
    completedTasks: todayCompleted.map((t) => ({
      id: t.id,
      text: t.text,
      category: t.category,
      priority: t.priority,
      completedAt: t.completedAt,
      wasLate: getCompletedDaysLate(t) > 0,
      daysLate: getCompletedDaysLate(t),
    })),
    habitsTotal,
    habitsDone,
    habitCompletionRate:
      habitsTotal > 0 ? Math.round((habitsDone / habitsTotal) * 100) : 0,
    pomodoroSessions: pomodoroData?.sessions || 0,
    pomodoroMinutes: pomodoroData?.minutes || 0,
    productivityScore: score,
    completionRate:
      todayTasks.length > 0
        ? Math.round((todayDone / todayTasks.length) * 100)
        : 0,
    personalNote: "",
    mood: null,
    autoGenerated: true,
  };
}

/**
 * Génère un rapport hebdomadaire à partir des rapports quotidiens de la semaine.
 */
export function generateWeeklyReport({ dailyReports, weekStart, weekEnd }) {
  if (!dailyReports || dailyReports.length === 0) return null;

  const tasksTotal = dailyReports.reduce((s, r) => s + (r.tasksTotal || 0), 0);
  const tasksDone = dailyReports.reduce((s, r) => s + (r.tasksDone || 0), 0);
  const habitsTotal = dailyReports.reduce(
    (s, r) => s + (r.habitsTotal || 0),
    0,
  );
  const habitsDone = dailyReports.reduce((s, r) => s + (r.habitsDone || 0), 0);
  const pomodoroSessions = dailyReports.reduce(
    (s, r) => s + (r.pomodoroSessions || 0),
    0,
  );
  const pomodoroMinutes = dailyReports.reduce(
    (s, r) => s + (r.pomodoroMinutes || 0),
    0,
  );
  const avgScore = Math.round(
    dailyReports.reduce((s, r) => s + (r.productivityScore || 0), 0) /
      dailyReports.length,
  );

  // Jour le plus productif
  const bestDay = dailyReports.reduce(
    (best, r) =>
      r.productivityScore > (best?.productivityScore || 0) ? r : best,
    null,
  );

  // Insights
  const insights = generateWeeklyInsights(dailyReports);

  return {
    type: "weekly",
    periodStart: weekStart,
    periodEnd: weekEnd,
    tasksTotal,
    tasksDone,
    completionRate:
      tasksTotal > 0 ? Math.round((tasksDone / tasksTotal) * 100) : 0,
    habitsTotal,
    habitsDone,
    habitCompletionRate:
      habitsTotal > 0 ? Math.round((habitsDone / habitsTotal) * 100) : 0,
    pomodoroSessions,
    pomodoroMinutes,
    productivityScore: avgScore,
    bestDayDate: bestDay?.periodStart,
    bestDayScore: bestDay?.productivityScore,
    dailyScores: dailyReports.map((r) => ({
      date: r.periodStart,
      score: r.productivityScore || 0,
      tasksDone: r.tasksDone || 0,
    })),
    insights,
    autoGenerated: true,
  };
}

/**
 * Génère des insights hebdomadaires basés sur les données.
 */
export function generateWeeklyInsights(dailyReports) {
  const insights = [];

  if (!dailyReports || dailyReports.length === 0) return insights;

  const avgScore =
    dailyReports.reduce((s, r) => s + (r.productivityScore || 0), 0) /
    dailyReports.length;
  const totalDone = dailyReports.reduce((s, r) => s + (r.tasksDone || 0), 0);
  const totalPomodoro = dailyReports.reduce(
    (s, r) => s + (r.pomodoroSessions || 0),
    0,
  );
  const avgHabitRate =
    dailyReports.reduce((s, r) => s + (r.habitCompletionRate || 0), 0) /
    dailyReports.length;

  // Jour le plus productif
  const bestDay = dailyReports.reduce(
    (best, r) =>
      r.productivityScore > (best?.productivityScore || 0) ? r : best,
    dailyReports[0],
  );
  const dayNames = [
    "Dimanche",
    "Lundi",
    "Mardi",
    "Mercredi",
    "Jeudi",
    "Vendredi",
    "Samedi",
  ];
  if (bestDay?.periodStart) {
    const dayName = dayNames[dayjs(bestDay.periodStart).day()];
    insights.push({
      icon: "⭐",
      text: `Ton jour le plus productif était le ${dayName} (${bestDay.productivityScore}/100)`,
    });
  }

  if (avgScore >= 70) {
    insights.push({
      icon: "🔥",
      text: `Excellente semaine ! Score moyen de ${Math.round(avgScore)}/100`,
    });
  } else if (avgScore >= 50) {
    insights.push({
      icon: "📈",
      text: `Bonne progression cette semaine, score moyen ${Math.round(avgScore)}/100`,
    });
  } else {
    insights.push({
      icon: "💡",
      text: `Cette semaine a été difficile. Essaie de définir moins de tâches mais de les finir toutes`,
    });
  }

  if (totalDone > 10) {
    insights.push({
      icon: "✅",
      text: `Impressionnant ! Tu as complété ${totalDone} tâches cette semaine`,
    });
  }

  if (totalPomodoro > 10) {
    insights.push({
      icon: "⏱",
      text: `${totalPomodoro} sessions Pomodoro — tu es très concentré !`,
    });
  }

  if (avgHabitRate >= 80) {
    insights.push({
      icon: "🏆",
      text: `Tes habitudes sont au top avec ${Math.round(avgHabitRate)}% de taux de complétion !`,
    });
  }

  return insights;
}

/**
 * Génère un badge mérité pour le mois.
 */
export function getMonthlyBadge(monthlyReport) {
  if (!monthlyReport) return null;
  const score = monthlyReport.productivityScore || 0;
  const streak = monthlyReport.maxStreak || 0;

  if (score >= 85 && streak >= 20)
    return { emoji: "👑", label: "Légende du mois", color: "#F59E0B" };
  if (score >= 75)
    return { emoji: "🏆", label: "Champion du mois", color: "#10B981" };
  if (score >= 60 && streak >= 14)
    return { emoji: "🔥", label: "Streak Master", color: "#EF4444" };
  if (score >= 50)
    return {
      emoji: "💪",
      label: "Warrior de la productivité",
      color: "#7C3AED",
    };
  if (score >= 30)
    return { emoji: "🌱", label: "En pleine croissance", color: "#06B6D4" };
  return { emoji: "🎯", label: "En cours de progression", color: "#6B7280" };
}

/**
 * Agrège les scores quotidiens en données pour la heatmap mensuelle.
 * Retourne un tableau de { date, score, level (0-4) }
 */
export function buildHeatmapData(dailyReports, year, month) {
  const daysInMonth = dayjs(
    `${year}-${String(month).padStart(2, "0")}-01`,
  ).daysInMonth();
  const reportMap = {};
  dailyReports.forEach((r) => {
    if (r.periodStart) reportMap[r.periodStart] = r;
  });

  const data = [];
  for (let d = 1; d <= daysInMonth; d++) {
    const dateStr = `${year}-${String(month).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
    const report = reportMap[dateStr];
    const score = report?.productivityScore || 0;
    // Level 0-4 pour la heatmap (comme GitHub)
    const level =
      score === 0 ? 0 : score < 25 ? 1 : score < 50 ? 2 : score < 75 ? 3 : 4;
    data.push({ date: dateStr, score, level, day: d });
  }
  return data;
}
