const quotes = [
  { text: "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.", author: "Winston Churchill" },
  { text: "La seule façon de faire du bon travail est d'aimer ce que vous faites.", author: "Steve Jobs" },
  { text: "Le futur appartient à ceux qui croient en la beauté de leurs rêves.", author: "Eleanor Roosevelt" },
  { text: "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles.", author: "Sénèque" },
  { text: "La discipline est le pont entre les objectifs et leur réalisation.", author: "Jim Rohn" },
  { text: "Chaque accomplissement commence par la décision d'essayer.", author: "John F. Kennedy" },
  { text: "Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur moment est maintenant.", author: "Proverbe chinois" },
  { text: "N'attendez pas. Le moment ne sera jamais parfait.", author: "Napoléon Hill" },
  { text: "Le génie, c'est 1% d'inspiration et 99% de transpiration.", author: "Thomas Edison" },
  { text: "Crois en toi et tout devient possible.", author: "Albert Einstein" },
  { text: "La persévérance n'est pas une longue course ; c'est beaucoup de petites courses l'une après l'autre.", author: "Walter Elliot" },
  { text: "L'éducation est l'arme la plus puissante pour changer le monde.", author: "Nelson Mandela" },
  { text: "Le seul endroit où le succès vient avant le travail, c'est dans le dictionnaire.", author: "Vidal Sassoon" },
  { text: "Ton avenir est créé par ce que tu fais aujourd'hui, pas demain.", author: "Robert Kiyosaki" },
  { text: "La motivation vous met en route. L'habitude vous fait continuer.", author: "Jim Ryun" },
  { text: "Qui veut peut. Qui ne veut pas, cherche des excuses.", author: "Socrate" },
  { text: "Le succès, c'est tomber sept fois et se relever huit.", author: "Proverbe japonais" },
  { text: "Ne juge pas chaque journée par la récolte que tu fais, mais par les graines que tu sèmes.", author: "Robert Louis Stevenson" },
  { text: "Les petits progrès quotidiens mènent à de grands résultats.", author: "Satya Nadella" },
  { text: "La seule limite à notre réalisation de demain sera nos doutes d'aujourd'hui.", author: "Franklin D. Roosevelt" },
  { text: "L'excellence n'est pas un acte, mais une habitude.", author: "Aristote" },
  { text: "Commencez là où vous êtes. Utilisez ce que vous avez. Faites ce que vous pouvez.", author: "Arthur Ashe" },
  { text: "Chaque expert a d'abord été un débutant.", author: "Helen Hayes" },
  { text: "Le courage n'est pas l'absence de peur, mais la capacité de vaincre ce qui fait peur.", author: "Nelson Mandela" },
  { text: "Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre toujours.", author: "Mahatma Gandhi" },
  { text: "Un voyage de mille lieues commence toujours par un premier pas.", author: "Lao Tseu" },
  { text: "Le savoir est la seule richesse que l'on peut donner sans s'appauvrir.", author: "Proverbe malien" },
  { text: "La connaissance parle, mais la sagesse écoute.", author: "Jimi Hendrix" },
  { text: "Fais de ta vie un rêve, et d'un rêve, une réalité.", author: "Antoine de Saint-Exupéry" },
  { text: "Ce qui ne te tue pas te rend plus fort.", author: "Friedrich Nietzsche" },
  { text: "Le talent gagne des matchs, mais le travail d'équipe et l'intelligence gagnent des championnats.", author: "Michael Jordan" },
  { text: "La patience est amère, mais son fruit est doux.", author: "Aristote" },
  { text: "Il n'y a pas de vent favorable pour celui qui ne sait pas où il va.", author: "Sénèque" },
  { text: "Sois le changement que tu veux voir dans le monde.", author: "Mahatma Gandhi" },
  { text: "Le plus grand risque est de ne prendre aucun risque.", author: "Mark Zuckerberg" },
  { text: "La différence entre l'impossible et le possible réside dans la détermination.", author: "Tommy Lasorda" },
  { text: "Celui qui déplace une montagne commence par déplacer de petites pierres.", author: "Confucius" },
  { text: "Le progrès est impossible sans changement, et ceux qui ne peuvent pas changer leur esprit ne peuvent rien changer.", author: "George Bernard Shaw" },
  { text: "La seule personne que tu es destiné à devenir est la personne que tu décides d'être.", author: "Ralph Waldo Emerson" },
  { text: "Il est toujours trop tôt pour abandonner.", author: "Norman Vincent Peale" },
  { text: "Le bonheur n'est pas une destination, c'est un mode de voyage.", author: "Margaret Lee Runbeck" },
  { text: "La simplicité est la sophistication suprême.", author: "Léonard de Vinci" },
  { text: "L'imagination est plus importante que le savoir.", author: "Albert Einstein" },
  { text: "Tout ce que l'esprit peut concevoir et croire, il peut le réaliser.", author: "Napoléon Hill" },
  { text: "La clé du succès est de commencer avant d'être prêt.", author: "Marie Forleo" },
  { text: "Fais aujourd'hui ce que les autres ne veulent pas faire, et demain tu feras ce que les autres ne peuvent pas faire.", author: "Jerry Rice" },
  { text: "Ne compare pas ton chapitre 1 au chapitre 20 de quelqu'un d'autre.", author: "Steve Bartlett" },
  { text: "La constance est la noblesse du résultat.", author: "Proverbe africain" },
  { text: "Apprendre sans réfléchir est vain. Réfléchir sans apprendre est dangereux.", author: "Confucius" },
  { text: "Investis en toi-même. Ta carrière est le moteur de ta richesse.", author: "Warren Buffett" },
  { text: "Les obstacles sont ces choses effrayantes que vous voyez quand vous quittez des yeux votre objectif.", author: "Henry Ford" },
  { text: "La créativité, c'est l'intelligence qui s'amuse.", author: "Albert Einstein" },
  { text: "Chaque jour est une nouvelle chance de changer ta vie.", author: "Anonyme" },
];

export function getQuoteOfTheDay() {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today - new Date(today.getFullYear(), 0, 0)) / (1000 * 60 * 60 * 24)
  );
  return quotes[dayOfYear % quotes.length];
}

export default quotes;
