import dayjs from 'dayjs';
import {
  collection, query, where, getDocs, addDoc,
} from 'firebase/firestore';
import { db } from '../firebase';
import { generateDailyReport, generateWeeklyReport } from './journalUtils';

/**
 * Rapport Scheduler — Génération automatique à minuit
 * 
 * Planifie la génération des rapports daily/weekly/monthly à 00h00 :
 * - Rapport quotidien de la veille
 * - Rapport hebdomadaire le lundi (pour la semaine précédente)
 * - Rapport mensuel le 1er du mois (pour le mois précédent)
 */

let scheduledTimeout = null;

/**
 * Calcule le délai en ms jusqu'à la prochaine minuit locale.
 */
function getMillisecondsUntilMidnight() {
  const now = new Date();
  const midnight = new Date(now);
  midnight.setHours(24, 0, 0, 0); // Next midnight
  return midnight.getTime() - now.getTime();
}

/**
 * Vérifie si un rapport existe déjà pour une période/type donnés.
 */
async function reportExists(uid, type, periodStart) {
  try {
    const q = query(
      collection(db, 'journal_entries'),
      where('uid', '==', uid)
    );
    const snap = await getDocs(q);
    return snap.docs.some((doc) => {
      const data = doc.data();
      return data.type === type && data.periodStart === periodStart;
    });
  } catch (e) {
    console.warn('Error checking report existence:', e);
    return false;
  }
}

/**
 * Génère le rapport mensuel à partir des rapports quotidiens.
 */
export function generateMonthlyReport({ dailyReports, year, month }) {
  if (!dailyReports || dailyReports.length === 0) return null;

  const monthStart = dayjs(`${year}-${String(month).padStart(2, '0')}-01`);
  const monthEnd = monthStart.endOf('month');

  const tasksTotal = dailyReports.reduce((s, r) => s + (r.tasksTotal || 0), 0);
  const tasksDone = dailyReports.reduce((s, r) => s + (r.tasksDone || 0), 0);
  const habitsTotal = dailyReports.reduce((s, r) => s + (r.habitsTotal || 0), 0);
  const habitsDone = dailyReports.reduce((s, r) => s + (r.habitsDone || 0), 0);
  const pomodoroSessions = dailyReports.reduce((s, r) => s + (r.pomodoroSessions || 0), 0);
  const pomodoroMinutes = dailyReports.reduce((s, r) => s + (r.pomodoroMinutes || 0), 0);
  const avgScore = Math.round(
    dailyReports.reduce((s, r) => s + (r.productivityScore || 0), 0) / dailyReports.length
  );

  const bestDay = dailyReports.reduce(
    (best, r) => (r.productivityScore > (best?.productivityScore || 0) ? r : best),
    null
  );

  const activeDays = dailyReports.filter(
    (r) => (r.tasksDone || 0) > 0 || (r.habitsDone || 0) > 0
  ).length;

  // Calculate max streak within the month
  const sortedDays = [...dailyReports]
    .filter((r) => (r.tasksDone || 0) > 0 || (r.habitsDone || 0) > 0)
    .sort((a, b) => (a.periodStart || '').localeCompare(b.periodStart || ''));

  let maxStreak = 0;
  let currentStreak = 0;
  let prevDate = null;

  sortedDays.forEach((r) => {
    if (prevDate && dayjs(r.periodStart).diff(dayjs(prevDate), 'day') === 1) {
      currentStreak++;
    } else {
      currentStreak = 1;
    }
    maxStreak = Math.max(maxStreak, currentStreak);
    prevDate = r.periodStart;
  });

  // Weekly scores for the month
  const weeklyScores = [];
  let currentWeek = monthStart.startOf('week');
  while (currentWeek.isBefore(monthEnd) || currentWeek.isSame(monthEnd, 'day')) {
    const ws = currentWeek;
    const we = ws.add(6, 'day');
    const weekReports = dailyReports.filter((r) => {
      const d = dayjs(r.periodStart);
      return d.isAfter(ws.subtract(1, 'day')) && d.isBefore(we.add(1, 'day'));
    });
    if (weekReports.length > 0) {
      const weekAvg = Math.round(
        weekReports.reduce((s, r) => s + (r.productivityScore || 0), 0) / weekReports.length
      );
      weeklyScores.push({
        weekStart: ws.format('YYYY-MM-DD'),
        score: weekAvg,
        days: weekReports.length,
      });
    }
    currentWeek = currentWeek.add(7, 'day');
  }

  return {
    type: 'monthly',
    periodStart: monthStart.format('YYYY-MM-DD'),
    periodEnd: monthEnd.format('YYYY-MM-DD'),
    tasksTotal,
    tasksDone,
    completionRate: tasksTotal > 0 ? Math.round((tasksDone / tasksTotal) * 100) : 0,
    habitsTotal,
    habitsDone,
    habitCompletionRate: habitsTotal > 0 ? Math.round((habitsDone / habitsTotal) * 100) : 0,
    pomodoroSessions,
    pomodoroMinutes,
    productivityScore: avgScore,
    bestDayDate: bestDay?.periodStart,
    bestDayScore: bestDay?.productivityScore,
    activeDays,
    totalDays: monthEnd.date(),
    maxStreak,
    weeklyScores,
    autoGenerated: true,
  };
}

/**
 * Exécute la génération des rapports.
 * Appelé à minuit ou quand l'app s'ouvre.
 */
async function executeReportGeneration(uid, tasks, habits, currentStreak) {
  const now = dayjs();
  const yesterday = now.subtract(1, 'day');
  const yesterdayStr = yesterday.format('YYYY-MM-DD');

  try {
    // 1. Rapport quotidien de la veille
    const dailyExists = await reportExists(uid, 'daily', yesterdayStr);
    if (!dailyExists) {
      const report = generateDailyReport({
        tasks,
        habits,
        pomodoroData: null,
        currentStreak,
        dateStr: yesterdayStr,
      });
      await addDoc(collection(db, 'journal_entries'), {
        uid,
        ...report,
        createdAt: new Date().toISOString(),
      });
      console.log('[ReportScheduler] Rapport quotidien généré pour', yesterdayStr);
    }

    // 2. Rapport hebdomadaire le lundi (pour la semaine dernière)
    if (now.day() === 1) { // Lundi
      const lastWeekStart = now.subtract(7, 'day').startOf('week').add(1, 'day'); // Lundi dernier
      const lastWeekEnd = lastWeekStart.add(6, 'day');
      const weekStartStr = lastWeekStart.format('YYYY-MM-DD');
      const weekEndStr = lastWeekEnd.format('YYYY-MM-DD');

      const weeklyExists = await reportExists(uid, 'weekly', weekStartStr);
      if (!weeklyExists) {
        // Get daily reports for the week
        const q = query(
          collection(db, 'journal_entries'),
          where('uid', '==', uid)
        );
        const snap = await getDocs(q);
        const weekDates = Array.from({ length: 7 }, (_, i) =>
          lastWeekStart.add(i, 'day').format('YYYY-MM-DD')
        );
        const dailyReports = snap.docs
          .map((doc) => doc.data())
          .filter((e) => e.type === 'daily' && weekDates.includes(e.periodStart));

        if (dailyReports.length > 0) {
          const report = generateWeeklyReport({
            dailyReports,
            weekStart: weekStartStr,
            weekEnd: weekEndStr,
          });
          if (report) {
            await addDoc(collection(db, 'journal_entries'), {
              uid,
              ...report,
              createdAt: new Date().toISOString(),
            });
            console.log('[ReportScheduler] Rapport hebdomadaire généré pour', weekStartStr);
          }
        }
      }
    }

    // 3. Rapport mensuel le 1er du mois (pour le mois dernier)
    if (now.date() === 1) {
      const lastMonth = now.subtract(1, 'month');
      const lastMonthYear = lastMonth.year();
      const lastMonthNum = lastMonth.month() + 1;
      const monthStart = dayjs(`${lastMonthYear}-${String(lastMonthNum).padStart(2, '0')}-01`);
      const monthStartStr = monthStart.format('YYYY-MM-DD');

      const monthlyExists = await reportExists(uid, 'monthly', monthStartStr);
      if (!monthlyExists) {
        const q = query(
          collection(db, 'journal_entries'),
          where('uid', '==', uid)
        );
        const snap = await getDocs(q);
        const monthPrefix = `${lastMonthYear}-${String(lastMonthNum).padStart(2, '0')}`;
        const dailyReports = snap.docs
          .map((doc) => doc.data())
          .filter((e) => e.type === 'daily' && (e.periodStart || '').startsWith(monthPrefix));

        if (dailyReports.length > 0) {
          const report = generateMonthlyReport({
            dailyReports,
            year: lastMonthYear,
            month: lastMonthNum,
          });
          if (report) {
            await addDoc(collection(db, 'journal_entries'), {
              uid,
              ...report,
              createdAt: new Date().toISOString(),
            });
            console.log('[ReportScheduler] Rapport mensuel généré pour', monthPrefix);
          }
        }
      }
    }
  } catch (error) {
    console.error('[ReportScheduler] Erreur lors de la génération:', error);
  }
}

/**
 * Démarre le scheduler de rapports.
 * Planifie la prochaine exécution à minuit.
 */
export function startReportScheduler(uid, tasks, habits, currentStreak) {
  // Stop any existing scheduler
  stopReportScheduler();

  if (!uid) return;

  // Execute immediately on startup (catch up on missed reports)
  executeReportGeneration(uid, tasks, habits, currentStreak);

  // Schedule for next midnight
  function scheduleNextMidnight() {
    const delay = getMillisecondsUntilMidnight();
    console.log(`[ReportScheduler] Prochaine génération dans ${Math.round(delay / 60000)} minutes`);

    scheduledTimeout = setTimeout(() => {
      executeReportGeneration(uid, tasks, habits, currentStreak);
      // Schedule the next day
      scheduleNextMidnight();
    }, delay);
  }

  scheduleNextMidnight();
}

/**
 * Arrête le scheduler.
 */
export function stopReportScheduler() {
  if (scheduledTimeout) {
    clearTimeout(scheduledTimeout);
    scheduledTimeout = null;
  }
}
